global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: torrix
    scrape_interval: 15s
    metrics_path: /metrics
    authorization:
      credentials: YOUR_TORRIX_API_KEY_HERE
    static_configs:
      - targets:
          - host.docker.internal:8088
